#!/usr/bin/env node
/**
 * Generate docs/capability-matrix.md: profile -> extensions -> task class.
 * Built from profiles/*.json + each extension.json + packages/core/sources.json (externals).
 * Deterministic; --check mode lets verify.mjs diff a fresh regen. (Epic 3 Sprint 3.3.)
 *
 * Usage:
 *   node packages/core/capability-matrix.mjs            # write docs/capability-matrix.md
 *   node packages/core/capability-matrix.mjs --check    # exit 1 if committed doc is stale
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { WORKSPACE_ROOT, DOCS_DIR, PROFILES_DIR, FIRST_PARTY_DIR, THIRD_PARTY_DIR, SKILLS_DIR, PROMPTS_DIR, THEMES_DIR, SCHEMA_DIR, POLICIES_DIR, SOURCES_PATH, CORE_DIR, ENV_EXAMPLE, extensionRelPath } from "./lib/paths.mjs";
import { readSources } from "./lib/sources.mjs";

const ROOT = WORKSPACE_ROOT;
const DOC_PATH = path.join(ROOT, "docs", "capability-matrix.md");

const PROFILE_ORDER = ["lite", "quick", "balanced", "long-horizon", "autonomous", "self-improving", "pentest"];

// Profile-level metadata (task class + tier band). Fixed, documented set of shipped profiles.
const PROFILE_META = {
  lite: { taskClass: "Low-context / small local models", tiers: "T0–T1" },
  quick: { taskClass: "Quick fix", tiers: "T0–T1" },
  balanced: { taskClass: "Daily coding", tiers: "T0–T2" },
  "long-horizon": { taskClass: "Multi-hour / multi-day", tiers: "T0–T3" },
  autonomous: { taskClass: "Set-and-walk-away", tiers: "T0–T3" },
  "self-improving": { taskClass: "Full / self-improving (experimental)", tiers: "T0–T4" },
  pentest: { taskClass: "Security engagement (strict)", tiers: "T0–T3+" },
};

function loadProfiles() {
  const out = {};
  for (const name of PROFILE_ORDER) {
    const p = path.join(PROFILES_DIR, `${name}.json`);
    if (fs.existsSync(p)) out[name] = JSON.parse(fs.readFileSync(p, "utf8"));
  }
  return out;
}

function loadManifests() {
  const meta = new Map(); // name -> { category, status, avenue }
  for (const { dir, avenue } of [
    { dir: FIRST_PARTY_DIR, avenue: "first-party" },
    { dir: THIRD_PARTY_DIR, avenue: "third-party" },
  ]) {
    if (!fs.existsSync(dir)) continue;
    for (const n of fs.readdirSync(dir)) {
      if (n.startsWith("_")) continue;
      const mp = path.join(dir, n, "extension.json");
      if (!fs.existsSync(mp)) continue;
      const m = JSON.parse(fs.readFileSync(mp, "utf8"));
      if (m === null || typeof m !== "object" || Array.isArray(m)) {
        console.warn(`[capability-matrix] WARN: ignoring non-object manifest: ${path.relative(ROOT, mp)}`);
        continue;
      }
      meta.set(m.name, { category: m.category, status: m.status, avenue });
    }
  }
  const sourcesPath = SOURCES_PATH;
  if (fs.existsSync(sourcesPath)) {
    for (const e of readSources(sourcesPath).external) {
      for (const name of e.provides ?? [e.name]) {
        if (!meta.has(name)) meta.set(name, { category: "external", status: "external", avenue: "external" });
      }
    }
  }
  return meta;
}

function render() {
  const profiles = loadProfiles();
  const manifests = loadManifests();

  // Membership set per extension.
  const membership = new Map();
  for (const name of PROFILE_ORDER) {
    for (const ext of profiles[name]?.include ?? []) {
      if (!membership.has(ext)) membership.set(ext, new Set());
      membership.get(ext).add(name);
    }
  }

  const lines = [
    "# Capability Matrix",
    "",
    "> Auto-generated by `packages/core/capability-matrix.mjs` from `profiles/*.json`, each",
    "> `extension.json`, and `packages/core/sources.json`. Do not hand-edit; run `npm run catalog`.",
    "",
    "## Profiles at a glance",
    "",
    "| Profile | Task class | Tiers | Extensions |",
    "|---|---|---|---|",
  ];
  for (const name of PROFILE_ORDER) {
    const p = profiles[name];
    if (!p) continue;
    const m = PROFILE_META[name] || { taskClass: "", tiers: "" };
    lines.push(`| \`${name}\` | ${m.taskClass} | ${m.tiers} | ${(p.include ?? []).length} |`);
  }
  lines.push("");

  // Extension x profile matrix, grouped by category.
  lines.push("## Extension × profile", "");
  lines.push(`| Extension | Category | Status | ${PROFILE_ORDER.map((p) => p.replace("-", "&#8209;")).join(" | ")} |`);
  lines.push(`|---|---|---|${PROFILE_ORDER.map(() => ":-:").join("|")}|`);

  const names = [...membership.keys()].sort((a, b) => {
    const ca = manifests.get(a)?.category || "zzz";
    const cb = manifests.get(b)?.category || "zzz";
    return ca === cb ? a.localeCompare(b) : ca.localeCompare(cb);
  });
  for (const name of names) {
    const meta = manifests.get(name) || { category: "external", status: "external" };
    const cells = PROFILE_ORDER.map((p) => (membership.get(name)?.has(p) ? "✓" : "·"));
    lines.push(`| \`${name}\` | ${meta.category} | ${meta.status} | ${cells.join(" | ")} |`);
  }
  lines.push("");
  lines.push(
    "Legend: ✓ enabled in that profile · `·` not included. `experimental`/`stub` extensions",
    "appear only in the experimental `self-improving` profile (see `SECURITY.md` and the",
    "roadmap). Externals (`pi-*`) install from `packages/core/sources.json`.",
    "",
  );
  return lines.join("\n");
}

export function capabilityMatrixContent() {
  return render();
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes("--check");
  const content = capabilityMatrixContent();
  if (check) {
    const current = fs.existsSync(DOC_PATH) ? fs.readFileSync(DOC_PATH, "utf8") : "";
    if (current !== content) {
      console.error("[capability-matrix] STALE: docs/capability-matrix.md differs from a fresh regen. Run: npm run catalog");
      process.exit(1);
    }
    console.log("[capability-matrix] OK: docs/capability-matrix.md is up to date.");
  } else {
    fs.writeFileSync(DOC_PATH, content);
    console.log(`[capability-matrix] Wrote ${path.relative(ROOT, DOC_PATH)}.`);
  }
}
