#!/usr/bin/env node
/**
 * Generate THIRD_PARTY_NOTICES.md from the vendored extensions' SOURCE.md files.
 *
 * Deterministic: no timestamps, no unordered iteration. Exports `noticesContent()`
 * so `verify.mjs` can fail on drift, and can be run directly:
 *
 *   node packages/core/gen-notices.mjs            # write the file
 *   node packages/core/gen-notices.mjs --check    # exit 1 if the committed file is stale
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { WORKSPACE_ROOT, THIRD_PARTY_DIR } from "./lib/paths.mjs";

const ROOT = WORKSPACE_ROOT;
const NOTICES_PATH = path.join(ROOT, "THIRD_PARTY_NOTICES.md");

// Upstream of most vendored extensions. The npm artifact does not ship its LICENSE, so the
// notice is reproduced from the upstream repository's LICENSE file, which reads
// "MIT License / Copyright (c) 2025 Mario Zechner" (checked against the repository's main branch
// on 2026-09-30).
const UPSTREAM_HOLDER = "2025 Mario Zechner";
const UPSTREAM_REPO = "https://github.com/earendil-works/pi";

const MIT_TEXT = `MIT License

Copyright (c) ${UPSTREAM_HOLDER}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.`;

// Strip the leading "# SOURCE" heading and surrounding blank lines so only the
// upstream/date/changes content is embedded.
function sourceBody(raw) {
  const lines = raw.replace(/\r\n/g, "\n").split("\n");
  let i = 0;
  while (i < lines.length && lines[i].trim() === "") i++;
  if (i < lines.length && /^#\s+/.test(lines[i])) i++;
  while (i < lines.length && lines[i].trim() === "") i++;
  return lines.slice(i).join("\n").trimEnd();
}

const CAVEMAN_CONCEPT_NOTE = [
  "- Concept attribution: the concept derives in turn from the `caveman` project by",
  "  Julius Brussee (https://github.com/JuliusBrussee/caveman), which is MIT-licensed with a",
  "  scope note that its engine directories (engine/, proxy/, rewriter/, browse/, mcp/,",
  "  shrink/ and others listed in its LICENSING.md) are under the Business Source License 1.1.",
  "  Nothing from those directories is used: the kit's `caveman` is a reimplementation of the",
  "  `pi-caveman` extension (MIT, Copyright (c) 2026), not a verbatim port of either project,",
  "  and is distributed under the kit's MIT license. The concept source is credited regardless.",
].join("\n");

function collectVendored() {
  if (!fs.existsSync(THIRD_PARTY_DIR)) return [];
  const entries = [];
  for (const name of fs.readdirSync(THIRD_PARTY_DIR).sort()) {
    const sourcePath = path.join(THIRD_PARTY_DIR, name, "SOURCE.md");
    if (!fs.existsSync(sourcePath)) continue;
    entries.push({ name, body: sourceBody(fs.readFileSync(sourcePath, "utf8")) });
  }
  return entries;
}

function render() {
  const vendored = collectVendored();
  const lines = [
    "# Third-Party Notices",
    "",
    "> Auto-generated by `packages/core/gen-notices.mjs` from",
    "> `packages/extensions/third_party/*/SOURCE.md`. Do not hand-edit; run",
    "> `node packages/core/gen-notices.mjs`.",
    "",
    "pi-system is distributed under the MIT license (see `LICENSE`). It vendors the",
    "third-party extensions listed below. Each entry records the upstream source and the",
    "changes made in this repository.",
    "",
    "## Upstream MIT notice",
    "",
    `Most vendored extensions are derived from \`@earendil-works/pi-coding-agent\` (${UPSTREAM_REPO}),`,
    "which is MIT-licensed. The upstream npm artifact does not ship its LICENSE file, so the",
    "notice is reproduced here from the upstream repository's LICENSE:",
    "",
    "```text",
    MIT_TEXT,
    "```",
    "",
    "## Vendored extensions",
    "",
  ];

  if (vendored.length === 0) {
    lines.push("_No vendored extensions found._", "");
  }

  for (const entry of vendored) {
    lines.push(`### \`${entry.name}\``, "", entry.body, "");
    if (entry.name === "caveman") lines.push(CAVEMAN_CONCEPT_NOTE, "");
  }

  return lines.join("\n");
}

export function noticesContent() {
  return render();
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes("--check");
  const content = noticesContent();
  if (check) {
    const current = fs.existsSync(NOTICES_PATH) ? fs.readFileSync(NOTICES_PATH, "utf8") : "";
    if (current !== content) {
      console.error("[gen-notices] STALE: THIRD_PARTY_NOTICES.md differs from a fresh regen. Run: node packages/core/gen-notices.mjs");
      process.exit(1);
    }
    console.log("[gen-notices] OK: THIRD_PARTY_NOTICES.md is up to date.");
  } else {
    fs.writeFileSync(NOTICES_PATH, content);
    console.log(`[gen-notices] Wrote ${path.relative(ROOT, NOTICES_PATH)}.`);
  }
}
