#!/usr/bin/env node
/**
 * Aggregate all avenues → docs/EXTENSIONS.md + registry.json
 * Usage: node packages/core/registry.mjs [--write-docs]
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { WORKSPACE_ROOT, FIRST_PARTY_DIR, THIRD_PARTY_DIR, SOURCES_PATH } from "./lib/paths.mjs";
import { readSources } from "./lib/sources.mjs";

const ROOT = WORKSPACE_ROOT;

/**
 * Read and JSON-parse a single extension manifest, naming the offending file on
 * failure. Pre-fix this was a bare JSON.parse whose SyntaxError identified no file.
 */
export function parseExtensionManifest(metaPath) {
  let raw;
  try {
    raw = fs.readFileSync(metaPath, "utf8");
  } catch (error) {
    throw new Error(`cannot read extension manifest ${metaPath}: ${error.message}`);
  }
  try {
    return JSON.parse(raw);
  } catch (error) {
    throw new Error(`invalid JSON in extension manifest ${metaPath}: ${error.message}`);
  }
}

/**
 * Collect every extension manifest from the two in-repo avenues plus the
 * configured external sources. Pure (no writes); shared by the generator and by
 * verify.mjs's drift gate.
 */
export function buildRegistryEntries() {
  const avenues = [
    { dir: FIRST_PARTY_DIR, rel: "packages/extensions/src", label: "First-party" },
    { dir: THIRD_PARTY_DIR, rel: "packages/extensions/third_party", label: "Vendored" },
  ];

  const entries = [];

  for (const { dir: baseDir, rel, label } of avenues) {
    if (!fs.existsSync(baseDir)) continue;
    for (const name of fs.readdirSync(baseDir)) {
      if (name.startsWith("_")) continue;
      const metaPath = path.join(baseDir, name, "extension.json");
      if (!fs.existsSync(metaPath)) continue;
      const meta = parseExtensionManifest(metaPath);
      entries.push({ ...meta, avenue: label, dir: `${rel}/${name}` });
    }
  }

  // External sources
  const sourcesPath = SOURCES_PATH;
  if (fs.existsSync(sourcesPath)) {
    const { external } = readSources(sourcesPath);
    for (const ext of external) {
      entries.push({
        name: ext.name, summary: ext.review ?? "(external)",
        category: "external", profiles: ext.profiles,
        avenue: `External (${ext.mode})`, dir: ext.source,
      });
    }
  }

  return entries;
}

/**
 * The exact bytes written to docs/EXTENSIONS.md. verify.mjs compares the committed
 * file against this so a hand-edited summary cannot pass with green CI (B-098).
 */
export function extensionsCatalogueContent(entries = buildRegistryEntries()) {
  // M-07 fix: the table previously had no Status column, so a quarantined stub (e.g.
  // mcp-router, profiles: []) looked like every other extension except for a blank
  // Profiles cell - nothing told a reader *why*. Surface each extension's manifest
  // `status` (stable/beta/experimental/stub) directly.
  const rows = entries.map(e =>
    `| \`${e.name}\` | ${e.avenue} | ${e.category} | ${e.status ?? "—"} | ${e.summary} | ${(e.profiles ?? []).join(", ") || "(none)"} |`
  );
  return `# Extensions Catalog\n\n> Auto-generated by \`packages/core/registry.mjs\`. Do not hand-edit.\n\nFor install package choices, see \`docs/profiles.md\`. For extension authoring, see \`docs/building-extensions.md\`.\n\n| Name | Avenue | Category | Status | Summary | Profiles |\n|---|---|---|---|---|---|\n${rows.join("\n")}\n`;
}

/**
 * Compare the committed docs/EXTENSIONS.md bytes against the generated catalogue.
 * Returns `{ stale: true }` on drift and `{ stale: false, error }` when generating
 * the catalogue throws (e.g. a malformed manifest), so a parse failure is never
 * masked as doc drift (B-104).
 */
export function extensionsCatalogueDrift(current) {
  try {
    if (current !== extensionsCatalogueContent()) return { stale: true };
    return { stale: false };
  } catch (error) {
    return { stale: false, error: String(error.message) };
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const entries = buildRegistryEntries();

  // Write registry.json
  const registryPath = path.join(ROOT, "docs", "registry.json");
  fs.mkdirSync(path.dirname(registryPath), { recursive: true });
  fs.writeFileSync(registryPath, `${JSON.stringify(entries, null, 2)}\n`);
  console.log(`[registry] Wrote ${registryPath}`);

  // Write EXTENSIONS.md
  if (process.argv.includes("--write-docs")) {
    const docsPath = path.join(ROOT, "docs", "EXTENSIONS.md");
    fs.writeFileSync(docsPath, extensionsCatalogueContent(entries));
    console.log(`[registry] Wrote ${docsPath}`);
  }
}
